"""add_platform_and_scheduled_at_to_drafts

Revision ID: 3ee4fb291951
Revises: 0c23d660630f
Create Date: 2026-04-05 01:28:32.995752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ee4fb291951"
down_revision: Union[str, Sequence[str], None] = "0c23d660630f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drafts",
        sa.Column(
            "platform", sa.String(length=50), server_default="telegram", nullable=False
        ),
    )
    op.add_column(
        "drafts", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drafts", "scheduled_at")
    op.drop_column("drafts", "platform")
    # ### end Alembic commands ###
